Repository googleapis/google-cloudevents, pull requests merged in 2020-09, with the labels that each got.

#60 feat: add quicktype tool
  generate-event-registry.sh
  proto/google/events/cloud/audit/v1/schema.json
  proto/google/events/cloud/pubsub/v1/schema.json
  tools/README.md
  tools/quicktype-wrapper/.eslintrc.json
  tools/quicktype-wrapper/.gitignore
  tools/quicktype-wrapper/.prettierrc.js
  tools/quicktype-wrapper/README.md
  tools/quicktype-wrapper/package-lock.json
  tools/quicktype-wrapper/package.json
  tools/quicktype-wrapper/src/index.ts
  tools/quicktype-wrapper/src/quickstype.ts
  tools/quicktype-wrapper/tsconfig.json
  tools/registry/Google.Events.Tools.GenerateRegistry/Google.Events.Tools.GenerateRegistry.csproj
  tools/registry/Google.Events.Tools.GenerateRegistry/Program.cs
  tools/registry/Google.Events.Tools.sln
Labels: api: events, cla: yes

#62 Update badge from Travis to GitHub Actions
  README.md
Labels: cla: yes

#63 feat: enable cli flags to quicktype wrapper
  tools/quicktype-wrapper/README.md
  tools/quicktype-wrapper/package-lock.json
  tools/quicktype-wrapper/package.json
  tools/quicktype-wrapper/src/index.ts
Labels: api: events, cla: yes

#65 fix: fix pub/sub message json schema
  proto/google/events/cloud/pubsub/v1/schema.json
Labels: cla: yes

#68 feat: add descriptions to main jsonschema fields
  proto/google/events/cloud/audit/v1/schema.json
  proto/google/events/cloud/pubsub/v1/schema.json
Labels: api: events, cla: yes

#71 chore: add CODEOWNERS and repo settings config
  .github/CODEOWNERS
  .github/sync-repo-settings.yaml
Labels: cla: yes

#70 Updated the quicktype-wrapper package
  tools/quicktype-wrapper/src/index.ts
Labels: api: eventarc, cla: yes

#69 feat: unwrap jsonschema one level
  proto/google/events/cloud/audit/v1/LogEntryData.json
  proto/google/events/cloud/audit/v1/schema.json
  proto/google/events/cloud/pubsub/v1/MessagePublishedData.json
  proto/google/events/cloud/pubsub/v1/schema.json
Labels: api: eventarc, cla: yes

#75 feat: update JSON Schema descriptions and references
  proto/google/events/cloud/audit/v1/LogEntryData.json
  proto/google/events/cloud/pubsub/v1/MessagePublishedData.json
Labels: api: eventarc, cla: yes

#77 feat: move jsonschemas to separate directory
  jsonschema/google/events/cloud/audit/LogEntryData.json
  jsonschema/google/events/cloud/pubsub/MessagePublishedData.json
Labels: api: eventarc, cla: yes
